owner: "Aldrin"
email: test@test.test
info: "Just a test blog"
#description
desc: "Testing, testing, 1, 2, 3..."


github: https://github.com/aldrinm
linkedin: https://linkedin.com/in/aldrinmisquitta
twitter: https://twitter.com/aldrinm
instagram:
